#' Create Summary Tables Using table1 with Custom Formatting
#'
#' `margot_make_tables` is a wrapper function for `table1::table1()` that simplifies the creation of summary tables.
#' It allows for custom variable labelling, formatting, factor conversion, and additional table options.
#' The function also performs data checks and provides user-friendly CLI alerts upon completion.
#'
#' @param data A data frame containing the dataset.
#' @param vars A character vector of variable names to include on the left-hand side of the table.
#' @param by A character vector of variable names to stratify the table by. Supports multiple variables for interactions.
#' @param labels A named character vector for custom variable labels. Names should correspond to variable names in `vars`.
#' @param factor_vars An optional character vector of variable names in `vars` to convert to factors for frequency tables.
#' @param table1_opts A list of additional options to pass to `table1::table1()`. For example, `list(overall = FALSE, transpose = TRUE)`.
#' @param format A character string specifying the output format. Options are `"html"` (default) and `"latex"`.
#' @param kable_opts A list of additional options to pass to `kable_styling()` when `format = "latex"`.
#'
#' @return A `table1` object or a LaTeX-formatted table generated by `kableExtra`.
#'
#' @importFrom table1 table1 setLabel t1kable
#' @importFrom dplyr mutate across
#' @importFrom stringr str_to_title
#' @importFrom cli cat_rule
#' @importFrom kableExtra kable_styling
#' @export
#'
#' @examples
#' \dontrun{
#' # Define variables
#' vars_list <- c(
#'   "age",
#'   "agreeableness",
#'   "belong",
#'   "born_nz",
#'   "conscientiousness",
#'   "education_level_coarsen",
#'   "employed",
#'   "eth_cat",
#'   "extraversion",
#'   "honesty_humility",
#'   "kessler_latent_anxiety",
#'   "kessler_latent_depression",
#'   "hours_children",
#'   "hours_commute",
#'   "hours_exercise",
#'   "hours_housework",
#'   "household_inc",
#'   "male",
#'   "neuroticism",
#'   "nz_dep2018",
#'   "nzsei_13_l",
#'   "openness",
#'   "parent",
#'   "partner",
#'   "political_conservative",
#'   "religion_identification_level",
#'   "rural_gch_2018_l",
#'   "rwa",
#'   "sample_frame_opt_in",
#'   "sdo",
#'   "short_form_health",
#'   "support"
#' )
#'
#' # Define labels
#' var_labels <- c(
#'   "sdo" = "Social Dominance Orientation",
#'   "born_nz" = "Born NZ",
#'   "rural_gch_2018_l" = "Rural GCH 2018 Levels",
#'   "eth_cat" = "Ethnicity",
#'   "rwa" = "Right Wing Authoritarianism",
#'   "support" = "Social Support (perceived)"
#' )
#'
#' # Create the summary table in LaTeX format
#' summary_tables_latex <- margot_make_tables(
#'   data = dat_long_amelia,
#'   vars = vars_list,
#'   by = "wave",
#'   labels = var_labels,
#'   factor_vars = c("rural_gch_2018_l", "eth_cat"),
#'   table1_opts = list(overall = FALSE, transpose = TRUE),
#'   format = "latex",
#'   kable_opts = list(
#'     booktabs = TRUE,
#'     longtable = TRUE,
#'     font_size = 10,
#'     latex_options = c("hold_position", "repeat_header", "striped", "longtable")
#'   )
#' )
#' }
margot_make_tables <- function(data, vars, by, labels = NULL, factor_vars = NULL, table1_opts = list(),
                               format = "html", kable_opts = list()) {
  # Ensure required packages are available
  required_packages <- c("table1", "dplyr", "stringr", "cli")
  missing_packages <- required_packages[!sapply(required_packages, requireNamespace, quietly = TRUE)]
  if (length(missing_packages) > 0) {
    stop(paste("The following required packages are not installed:",
               paste(missing_packages, collapse = ", ")))
  }

  # packages
  library(table1)
  library(dplyr)
  library(stringr)
  library(cli)

  # if format is latex, ensure kableExtra is installed
  if (format == "latex") {
    if (!requireNamespace("kableExtra", quietly = TRUE)) {
      stop("Package 'kableExtra' is required for LaTeX formatting but is not installed.")
    }
    library(kableExtra)
  }

  # data checks
  missing_by_vars <- by[!by %in% names(data)]
  if (length(missing_by_vars) > 0) {
    stop(paste("The following 'by' variables are missing in the data:",
               paste(missing_by_vars, collapse = ", ")))
  }

  # check for missingness in 'by' variables
  for (var in by) {
    if (any(is.na(data[[var]]))) {
      stop(paste("Variable", var, "has missing values. Please handle missingness before proceeding."))
    }
  }

  # ensure all vars exist in data
  missing_vars <- vars[!vars %in% names(data)]
  if (length(missing_vars) > 0) {
    stop(paste("The following variables are missing in the data:",
               paste(missing_vars, collapse = ", ")))
  }

  # function to format variable names nicely
  format_var_name <- function(name) {
    name %>%
      gsub("_", " ", .) %>%
      stringr::str_to_title() %>%
      trimws()
  }

  # convert specified variables to factors first
  if (!is.null(factor_vars)) {
    missing_factor_vars <- factor_vars[!factor_vars %in% vars]
    if (length(missing_factor_vars) > 0) {
      stop(paste("The following 'factor_vars' are not in 'vars':",
                 paste(missing_factor_vars, collapse = ", ")))
    }
    data <- data %>%
      dplyr::mutate(
        dplyr::across(
          .cols = all_of(factor_vars),  # Updated to use all_of()
          .fns = ~ as.factor(.x),
          .names = "{.col}"
        )
      )
  }

  # apply custom labels where provided
  if (!is.null(labels)) {
    # Ensure 'labels' is a named vector
    if (is.null(names(labels))) {
      stop("'labels' must be a named character vector with names corresponding to variable names in 'vars'.")
    }

    # assign custom labels using table1::setLabel
    data <- data %>%
      dplyr::mutate(
        dplyr::across(
          .cols = intersect(names(labels), vars),
          .fns = ~ table1::setLabel(.x, labels[[cur_column()]]),
          .names = "{.col}"
        )
      )
  }

  # assign formatted labels for variables without custom labels
  data <- data %>%
    dplyr::mutate(
      dplyr::across(
        .cols = setdiff(vars, names(labels)),
        .fns = ~ table1::setLabel(.x, format_var_name(cur_column())),
        .names = "{.col}"
      )
    )

  # create formula for table1
  lhs <- paste(vars, collapse = " + ")
  rhs <- paste(by, collapse = " * ")
  formula <- as.formula(paste("~", lhs, "|", rhs))

  # merge additional options
  table1_args <- c(list(x = formula, data = data), table1_opts)  # Updated 'formula' to 'x'

  # generate the table1 object
  table <- tryCatch(
    {
      do.call(table1::table1, table1_args)
    },
    error = function(e) {
      stop("Error in generating table1: ", e$message)
    }
  )

  # If format is latex, process with t1kable and kable_styling
  if (format == "latex") {
    if (!requireNamespace("kableExtra", quietly = TRUE)) {
      stop("Package 'kableExtra' is required for LaTeX formatting but is not installed.")
    }
    library(kableExtra)

    # Apply t1kable and kable_styling with provided options
    table <- table1::t1kable(
      table,
      format = "latex",
      booktabs = ifelse(!is.null(kable_opts$booktabs), kable_opts$booktabs, TRUE),
      longtable = ifelse(!is.null(kable_opts$longtable), kable_opts$longtable, TRUE)
    ) %>%
      kableExtra::kable_styling(
        font_size = ifelse(!is.null(kable_opts$font_size), kable_opts$font_size, 10),
        latex_options = ifelse(!is.null(kable_opts$latex_options),
                               kable_opts$latex_options,
                               c("hold_position", "repeat_header", "striped", "longtable"))
      )
  }

  # CLI alert
  cli::cat_rule("Summary Table Created Successfully! 😊")

  return(table)
}
