#' Create Combined Tables for Subset Condition Using GRF Models
#'
#' This function calculates new evaluation tables for specified outcome variables
#' using a subset condition, and combines them into a single data frame. It uses
#' the models generated by `margot_run_models_grf` to create these tables.
#'
#' @param models A list of model results from `margot_run_models_grf`.
#' @param outcome_vars A character vector of outcome variable names.
#' @param subset_condition A logical vector indicating the subset of data to use. Default is NULL.
#' @param scale A character string indicating the scale to use in `margot_model_evalue`. Default is "RD".
#'
#' @return A data frame combining all custom evaluation tables for the specified subset condition.
#'
#' @details
#' The function uses `margot_model_evalue` to calculate evaluation metrics for each model
#' in the subset of data specified by `subset_condition`.
#'
#' @note
#' Ensure that the `models` list contains results for all specified `outcome_vars`,
#' otherwise some outcomes may be omitted from the final table.
#'
#' @seealso
#' \code{\link{margot_run_models_grf}} for generating the initial models.
#'
#' @importFrom margot margot_model_evalue
#'
#' @examples
#' \dontrun{
#' # Assuming result_psychological_well_being is your results object from the previous function
#' subset_condition <- X[, "t0_self_esteem_z"] < 1
#' combined_table_subset <- margot_subset_table_grf(
#'   models = result_psychological_well_being$results,
#'   outcome_vars = outcomes_psychological_well_being,
#'   subset_condition = subset_condition,
#'   scale = "RD"
#' )
#' print(combined_table_subset)
#' }
#'
#' @export
margot_subset_table_grf <- function(models, outcome_vars, subset_condition = NULL, scale = "RD") {
  tables <- list()

  for (outcome in outcome_vars) {
    model_name <- paste0("model_", outcome)

    if (model_name %in% names(models)) {
      model <- models[[model_name]]$model
      new_name <- outcome

      # calculate new evaluation table for the subset
      custom_table <- margot::margot_model_evalue(model, scale = scale, new_name = new_name, subset = subset_condition)

      # store custom table for binding later
      tables[[outcome]] <- custom_table
    }
  }

  # bind tables for outcomes within each domain
  combined_table <- do.call(rbind, tables)

  return(combined_table)
}
